Mensagens no app
RodolfoSilva/DeVryCalc pull request #39
Opened 2017-07-21 00:31 UTC by viniciusvts

Suavização da fonte na mensagem: 'Não foi dessa vez sorte na próxima', a mensagem também será exibida se já estiver perdido antes de fazer a substitutiva da ap1 ou ap2.

Adição da mensagem: 'Parabéns, você está passado' caso o aluno já esteja passado na disciplina com apenas duas provas realizadas. A mensagem também será exibida se já estiver passado antes de fazer a substitutiva da ap1 ou ap2.

2017-07-21 00:43 UTC, RodolfoSilva commented
Bom trabalho @viniciusvts, ficou :100:0

2017-07-21 00:44 UTC, RodolfoSilva requested changes
Bom trabalho @viniciusvts, ficou :100:0

2017-07-21 00:44 UTC, RodolfoSilva commented on src/pages/home/home.html
> +      Parabéns, já está passado.
Acho que seria interessante a gente avisar ao cara que se ele for aprovado na AP1 e na AP2, mesmo estando aprovado, ele tem que fazer a AP3. Porque se ele não fizer a AP3 ele pode perder.

2017-07-21 00:44 UTC, RodolfoSilva commented on src/pages/home/home.html
> +      <previsao-nota *ngIf="disciplina.notas.notaParaAP1 > 0" titulo="Necessário tirar na AP1" [nota]="disciplina.notas.notaParaAP1"></previsao-nota>
Bala :+1: ... Dá pra fazer um pequeno refactor nessa parte @viniciusvts, veja o component https://github.com/RodolfoSilva/DeVryCalc/blob/master/src/components/previsao-nota/previsao-nota.ts 
Essa condição de verificar se é maior que 0 pode ser adicionado lá no componente de previsão de nota.

2017-07-21 00:48 UTC, vaporwavie commented
Boa, @viniciusvts! Fico feliz que tenha nos enviado o PR, o projeto é pra isso mesmo :D 
+1 no comentário de Rodolfo com as alterações que ele sugeriu. Dá uma olhada no componente de previsão de notas, você pode tratar a condição que você colocou no if por lá, ao invés de usar logo na diretiva.

2017-07-21 01:05 UTC, viniciusvts commented on src/pages/home/home.html
> +      <previsao-nota *ngIf="disciplina.notas.notaParaAP1 > 0" titulo="Necessário tirar na AP1" [nota]="disciplina.notas.notaParaAP1"></previsao-nota>
Com um boolean seria suficiente?

2017-07-21 01:05 UTC, viniciusvts commented on src/pages/home/home.html
> +      Parabéns, já está passado.
Feito!

2017-07-21 01:06 UTC, viniciusvts commented on src/pages/home/home.html
> +      <previsao-nota *ngIf="disciplina.notas.notaParaAP1 > 0" titulo="Necessário tirar na AP1" [nota]="disciplina.notas.notaParaAP1"></previsao-nota>
e usar um [hidden]="oBooleanAqui"
é suficiente?

2017-07-21 01:11 UTC, RodolfoSilva commented on src/pages/home/home.html
> +      <previsao-nota *ngIf="disciplina.notas.notaParaAP1 > 0" titulo="Necessário tirar na AP1" [nota]="disciplina.notas.notaParaAP1"></previsao-nota>
Pode ser também...

Mas o que eu estava sugerindo, era adicionar essa condição direto no component:

https://github.com/RodolfoSilva/DeVryCalc/blob/master/src/components/previsao-nota/previsao-nota.ts#L8

```
nota !== null && nota <= 10
```

Porque ele hoje já verifica se é diferente de nullo e menor ou igual a 10, no caso vc iria adicionar a verificação se nota for maior que 0.

2017-07-21 01:21 UTC, viniciusvts commented on src/pages/home/home.html
> +      <previsao-nota *ngIf="disciplina.notas.notaParaAP1 > 0" titulo="Necessário tirar na AP1" [nota]="disciplina.notas.notaParaAP1"></previsao-nota>
Feito! Obrigado grande Jedi

2017-07-21 15:41 UTC, viniciusvts commented
Feito!

2017-07-21 17:07 UTC, RodolfoSilva approved these changes

2017-07-25 09:59 UTC, RodolfoSilva commented
@viniciusvts tá tudo ok, só não aprovei o pull request ainda porque preciso arrumar o CI que tá quebrado. Assim que eu arrumar faço o merge. :smile:

2017-07-25 10:07 UTC, viniciusvts commented
Valeu!

2018-01-20 21:49 UTC, RodolfoSilva commented
Obrigado @viniciusvts irei migrar esse PR para a nova versão.

2018-02-13 16:14 UTC, RodolfoSilva commented
@viniciusvts estava olhando as modificações que você fez na versão antiga [**4ebacb9**](https://github.com/RodolfoSilva/DeVryCalc/compare/4ebacb9e331679552a55d42c62a944be66d88a74?expand=1). Tentarei fazer isso na nova versão e no PR indicarei que foi você quem contribuiu. Mas caso você queira fazer, pode ficar a vontade. Vlw pela contribuição. 👍 😄

2018-02-18 03:06 UTC, viniciusvts commented
Flw, nao conheço o react
:(
irei dar um olhada depois

2025-02-05 20:12 UTC, closed without merging